language: generic
matrix:
   include:
      # Test Ubuntu Linux 14.04
       - os: linux
         dist: trusty
         sudo: required
       - os: osx
         osx_image: xcode11.4
install:
    - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
    - swift test -c release -Xswiftc -enable-testing -Xswiftc -DCI -Xswiftc -Xfrontend -Xswiftc -solver-memory-threshold -Xswiftc -Xfrontend -Xswiftc 999999999
